#
# @lc app=leetcode.cn id=756 lang=python3
#
# [756] 金字塔转换矩阵
#
from functools import lru_cache
from typing import List
from itertools import product

# @lc code=start
class Solution:
    def pyramidTransition(self, bottom: str, allowed: List[str]) -> bool:
        allowedict = dict()
        for a, b, c in allowed:
            if (a, b) in allowedict:
                allowedict[(a, b)].add(c)
            else:
                allowedict[(a, b)] = set(c)

        @lru_cache(None)
        def _getUpper(bottom: tuple) -> bool:
            if len(bottom) == 2:
                return bottom in allowedict
            try:
                uppers = [allowedict[i] for i in zip(bottom, bottom[1:])]
            except KeyError:
                # no found
                return False
            for block in product(*uppers):
                if _getUpper(block):
                    return True
            else:
                return False

        return _getUpper(tuple(bottom))


# @lc code=end

if __name__ == "__main__":
    r = Solution().pyramidTransition("BCD", ["BCG", "CDE", "GEA", "FFF"])
    print(r)
    b = "DAAAAD"
    a = [
        "DAD",
        "DAE",
        "DAB",
        "DAF",
        "DAC",
        "EAD",
        "EAE",
        "EAB",
        "EAF",
        "EAC",
        "BAD",
        "BAE",
        "BAB",
        "BAF",
        "BAC",
        "FAD",
        "FAE",
        "FAB",
        "FAF",
        "FAC",
        "CAD",
        "CAE",
        "CAB",
        "CAF",
        "CAC",
        "ADD",
        "ADE",
        "ADB",
        "ADF",
        "ADC",
        "AED",
        "AEE",
        "AEB",
        "AEF",
        "AEC",
        "ABD",
        "ABE",
        "ABB",
        "ABF",
        "ABC",
        "AFD",
        "AFE",
        "AFB",
        "AFF",
        "AFC",
        "ACD",
        "ACE",
        "ACB",
        "ACF",
        "ACC",
        "AAD",
        "AAE",
        "AAB",
        "AAF",
        "AAC",
        "AAA",
    ]
    b = "ABBBBBBG"
    a = [
        "BDD",
        "BFB",
        "FDA",
        "CCC",
        "FBD",
        "FBG",
        "EEB",
        "GBA",
        "CFB",
        "ECB",
        "GDA",
        "ECC",
        "EFE",
        "FCA",
        "DBA",
        "FAD",
        "BEE",
        "GEC",
        "CFC",
        "CFD",
        "BCG",
        "CAC",
        "FCC",
        "GAC",
        "CAG",
        "CFF",
        "BEC",
        "EAD",
        "GBE",
        "FEG",
        "BDC",
        "GBF",
        "FBB",
        "FBE",
        "DDG",
        "FDF",
        "EDF",
        "FAF",
        "BEB",
        "DDE",
        "EEA",
        "FAG",
        "GDC",
        "DFE",
        "CDB",
        "DFD",
        "GDD",
        "DAF",
        "ECE",
        "DBG",
        "DDD",
        "EFG",
        "FAC",
        "FEC",
        "GED",
        "DEE",
        "CCF",
        "EFD",
        "FDE",
        "GDF",
        "ECG",
        "DAE",
        "FCG",
        "DCA",
        "EAF",
        "EED",
        "EEE",
        "FEA",
        "BFG",
        "EAA",
        "GDE",
        "CEB",
        "FAE",
        "BDE",
        "EBB",
        "GFD",
        "DBB",
        "BFD",
        "EFF",
        "DAD",
        "CDC",
        "DCD",
        "FFD",
        "DBD",
        "EFA",
        "BCB",
        "ECF",
        "CFA",
        "GFF",
        "CFG",
        "EEG",
        "DAG",
        "CAE",
        "FED",
        "CCA",
        "EDE",
        "FDG",
        "BEF",
        "FDD",
        "BEG",
        "FFE",
        "DDC",
        "BCE",
        "GAA",
        "GFE",
        "FFF",
        "CFE",
        "BDF",
        "DFG",
        "DEF",
        "FEF",
        "GEE",
        "EAB",
        "GDB",
        "CEE",
        "BDA",
        "DEG",
        "DEC",
        "GCG",
        "DFB",
        "EFB",
        "GAB",
        "CDF",
        "CAF",
        "BAB",
        "GCC",
        "DDA",
        "CDD",
        "FCB",
        "DAA",
        "GBG",
        "BAC",
        "GCE",
        "GAG",
        "EAE",
        "EBG",
        "GBD",
        "BFE",
        "CCD",
        "EDD",
        "FCD",
        "FBC",
        "DEB",
        "EDG",
        "GEA",
        "EBE",
        "GDG",
        "DBE",
        "BCD",
        "GBB",
        "FEB",
        "DED",
        "CAD",
        "EDB",
        "CED",
        "GCD",
        "BFC",
        "GAE",
        "CEG",
        "EEC",
        "FEE",
        "GCA",
        "FCF",
        "ECD",
        "DCC",
        "BDB",
        "EBD",
        "DCE",
        "BAE",
        "FFG",
        "DDF",
        "DCF",
        "BED",
        "CAA",
        "BCF",
        "GBC",
        "CCB",
        "BCC",
        "GFC",
        "FFB",
        "DFA",
        "BBA",
        "BBB",
        "BBC",
        "BBD",
        "BBE",
        "BBF",
        "BBG",
        "AAA",
        "ABA",
        "ACA",
        "ADA",
        "AEA",
        "AFA",
        "BGG",
        "CGG",
        "DGG",
        "EGG",
        "FGG",
        "GGG",
    ]
    r = Solution().pyramidTransition(b, a)
    print(r)
